import styled from 'styled-components';

export const Container = styled.button`
  width: 100%;
  color: #fff;
  background-color: #0f62fe;
  border: 1px solid transparent;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  padding: 1rem;
  font-size: 0.875rem;
  font-weight: 400;
  line-height: 1.29;
  letter-spacing: 0.16px;
  position: relative;
  display: inline-flex;
  flex-shrink: 0;
  align-items: center;
  justify-content: space-between;
  min-height: 3rem;
  height: 64px;
  margin: 0;
  padding: calc(0.875rem - 3px) 63px calc(0.875rem - 3px) 15px;
  text-align: left;
  text-decoration: none;
  vertical-align: top;
  border-radius: 0;
  outline: none;
  cursor: pointer;
`;
